### ISSUE TITLE
Restructuring

### ISSUE THREAD

**Issue by narendravaghela** [sprintcube/docker-compose-lamp#103]
I have seen and also got a few suggestions about the number of branches for different PHP versions.

Can we restructure this to have a common configuration using .env file for using a different version of each software? For example, in `.env` file,
```
PHP_VERSION: 7.2
```
And have a separate image for PHP 7.2 which will be loaded through `docker-compose.yml`.

We can take a reference from https://laradock.io/documentation/

@MrOffline77 Please let me know your thoughts on this.

This way, we can have a better LAMP stack with more customization options. And we don't have to switch branches for different versions.

**Comment by MrOffline77** [comment]
In general I agree with you that one branch with a customizable PHP Version through a .env would be much easier to handle and maintain. 
Laradock is able to this, because they build their own php images. Therefore they can manipulate the variables. 

Maybe we can create some kind of mapping with nested env vars: 

in .env `PHP_VERSION: 7.4`-> what leads to something like this: 

```
version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver-${PHP_VERSION}
    container_name: 'webserver-'${PHP_VERSION}
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
```

Then we would have multiple webserver dockerfiles 
```
⇒  tree
.
├── mysql
│   └── Dockerfile
├── webserver-5.4
│   └── Dockerfile
├── webserver-5.6
│   └── Dockerfile
├── webserver-7.0
│   └── Dockerfile
├── webserver-7.1
│   └── Dockerfile
├── webserver-7.2
│   └── Dockerfile
├── webserver-7.3
│   └── Dockerfile
└── webserver-7.4
    └── Dockerfile
```

This could work not sure but we could give a try :D. What do think about this @narendravaghela ?
