### ISSUE TITLE
Can't connect to mysql via Wordpress

### ISSUE THREAD

**Issue by NickRaleigh** [sprintcube/docker-compose-lamp#12]
Hello,
Can't seem to get Wordpress to work with this stack. I can create a new database via phpmyadmin, but Wordpress cannot find the docker container db. I've tried modifying both the `docker-compose.yml` file as well as the `wp-config.php`.

![image](https://user-images.githubusercontent.com/23318932/48664492-6eb44980-ea5c-11e8-931b-7689d9180cd9.png)

`docker-compose.yml`:
```
version: "3"

services:
  webserver:
    build: 
      context: ./bin/webserver
    container_name: 'pcha-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'pcha-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes: 
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: pcha_local
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'pcha-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
```

`wp-config.php`: I've tried modifying the `define('DB_HOST', ` line to `localhost:3306` as well (to match the port of the container).

```
define('DB_NAME', 'pcha_local');

/** MySQL database username */
define('DB_USER', 'root');

/** MySQL database password */
define('DB_PASSWORD', 'tiger');

/** MySQL hostname */
define('DB_HOST', 'localhost');

/** Database Charset to use in creating database tables. */
define('DB_CHARSET', 'utf8');

/** The Database Collate type. Don't change this if in doubt. */
define('DB_COLLATE', '');
```
