### ISSUE TITLE
Installing composer as well

### ISSUE THREAD

**Issue by ankit7540** [sprintcube/docker-compose-lamp#158]
Could someone clarify how to go ahead with the installation of composer as well, within this docker-compose instance.

I added the following at the end of the `docker-compose.yml`  :

```
  composer:
    restart: 'no'
    container_name: composer
    image: "composer"
    command: install
    volumes:
      - ./config/composer:/app
```
Inside the folder, `/config/composer` I place `composer.json` file, listing the packages to include.
Upon starting this, the composer instance gives error and does not start. 
The error;

```
composer      | install: missing file operand
composer      | Try 'install --help' for more information.
```
followed by,
`composer exited with code 1`

Thank you.

**Comment by ankit7540** [comment]
I got it working by including the following in yml file.

```
  composer:
    restart: 'no'
    container_name: composer
    image: "composer"
    command: install --no-suggest
    volumes:
      - ./www/admin/php:/app
```

with `compose.json` in `./www/admin/php`
