### ISSUE TITLE
 [BUG] phpmyadmin unsecure, no username or password needed

### ISSUE THREAD

**Issue by GiHey** [sprintcube/docker-compose-lamp#180]
**which Branch / PHP Version are you using ?**
php8

**Steps to reproduce**
1. Go to 'your IP on the PHPmyadmin-Port'
2. You will be locked in without password

I fixed it by editing the the environment variables for "phpmyadmin" in the docker-compose.yml. I deleted the whole login variables:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: '${COMPOSE_PROJECT_NAME}-phpmyadmin'
    links:
      - database
    environment:
      PMA_HOST: database
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}
    ports:
      - '${HOST_MACHINE_PMA_PORT}:80'
    volumes:
      - /sessions
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini

docker -v
Docker version 20.10.9, build c2ea9bc

**Comment by MrOffline77** [comment]
Hi, thats not a Bug in my opinion since this is development environment is supposed to run on localhost for development purposes only.

**Comment by alainseys** [comment]
@GiHey this is not a bug since this is a development enviroment it is ok to get logged in to the phpmyadmin the stack is not intented to use on a production system on production you should indeed use env variables , but the question is then if the stack is the best use for it...

**Comment by alainseys** [comment]
@MrOffline77 this can be closed i guess

**Comment by joechea-aupp** [comment]
for those who still looking on answer to have phpmyadmin required password when access uncomment the follow code on `docker-compose.yml`

```yml
phpmyadmin:
    image: phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      #PMA_USER: root
      #PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      UPLOAD_LIMIT: ${UPLOAD_LIMIT}
      MEMORY_LIMIT: ${MEMORY_LIMIT}

```

like myself i built my development box on an online remote server 😉😏
