### ISSUE TITLE
Initialize mysql with *.sql script

### ISSUE THREAD

**Issue by johnoliv** [sprintcube/docker-compose-lamp#26]
I tried in several different ways to initialize the MySQL with *.sql script.
I tried to alter the Dockerfile or just alter the compose.yml, and, just not work... 

What the correct way to initialize MySQL with a *.sql script in this project?
Thanks a lot.

**Comment by yapsr** [comment]
@johnoliv 

In stead of mysql I use mariadb: https://hub.docker.com/_/mariadb/#initializing-a-fresh-instance

```
  mysql:
    build: ./bin/mysql
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./var/lib/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./var/log/mysql}:/var/log/mysql
      - ./config/mysql/initdb:/docker-entrypoint-initdb.d

```
