### ISSUE TITLE
phpmyadmin log in without a password!

### ISSUE THREAD

**Issue by defeval** [sprintcube/docker-compose-lamp#271]
Hi! phpmyadmin opens within the local network without entering a password. How to make access only by password?

**Comment by ostgardh** [comment]
Anyone know how enable password login?

**Comment by gilluc** [comment]
me too!

**Comment by blastg** [comment]
Modify configuration: (nnnnnnnnnnn) is your phpmyadmin container id (view with docker ps)
```
docker cp nnnnnnnnnnn:/etc/phpmyadmin/config.inc.php config.inc.php
vi config.inc.php
```
modify from 'config'

```
   if (isset($_ENV['PMA_USER'])) {
        $cfg['Servers'][$i]['auth_type'] = 'config';
```

to 'cookie'

```
   if (isset($_ENV['PMA_USER'])) {
        $cfg['Servers'][$i]['auth_type'] = 'cookie';
```
then copy config file in container
```
docker cp config.inc.php nnnnnnnnnnn:/etc/phpmyadmin/config.inc.php
```
edit docker-compose.yml commenting out PMA_USER and PMA_PASSWORD

`vi docker-compose.yml`

```
  phpmyadmin:
    image: phpmyadmin
    container_name: "${COMPOSE_PROJECT_NAME}-phpmyadmin"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
        #PMA_USER: root
        #PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
```
Restart phpmyadmin docker container
`docker restart nnnnnnnnnnn`
