### ISSUE TITLE
Writing permissions

### ISSUE THREAD

**Issue by sk1ter** [sprintcube/docker-compose-lamp#67]
I have a problem with write permission on /var/www/html directory. 
```
Warning: file_put_contents(aaa.txt): failed to open stream: Permission denied in /var/www/html/index.php on line 69
```
How can I fix it?

**Comment by MrOffline77** [comment]
Are you using windows or Ubuntu ? Which PHP version do you use ?

**Comment by javlonbek-sharipov** [comment]
Hi! I am using Ubuntu 18.04, Docker version 18.09.7 build 2d0083d

**Comment by MrOffline77** [comment]
@javlonbek-sharipov this sound like #41 does the steps there help you with your problem ?

**Comment by wi1w** [comment]
You can try pass rw permissions to container.
```
webserver:
    build: 
      context: ./bin/webserver
    container_name: 'png-webserver'
    restart: 'always'
    ports:
      - "80:80"
      - "443:443"
    links: 
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-./www}:/var/www/html:rw
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
```

Try modify volume with files with ```:rw```

Reply if helps
